CREATE TABLE customer
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    surname      VARCHAR(255),
    birthday     TIMESTAMP,
    phone_number BIGINT,
    loyal        BOOLEAN,
    created_date TIMESTAMP,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);