CREATE TABLE item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    weight       DOUBLE PRECISION,
    sector       INT,
    customer_id  BIGINT,
    created_date TIMESTAMP,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

ALTER TABLE item
    ADD CONSTRAINT FK_ITEM_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);